import { Card } from "@/shared/model/types";
export const cards: Card[] = [
  {
    id: 1,
    title: "Клубничный макарон",
    description: "Нежный десерт с клубничной начинкой",
    price: 150,
    tastes: ["клубника"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#ff004c", Bottom: "#ff004c", Center: "#ffdada" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 2,
    title: "Фисташковый макарон",
    description: "Ореховый вкус с нежным кремом",
    price: 170,
    tastes: ["фисташка"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#9ac791", Bottom: "#9ac791", Center: "#e3f0d7" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 3,
    title: "Шоколадный макарон",
    description: "Насыщенный шоколадный вкус с ганашем",
    price: 160,
    tastes: ["шоколад"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#5c3a21", Bottom: "#5c3a21", Center: "#d9b48f" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 4,
    title: "Лимонный макарон",
    description: "Цитрусовая свежесть с лимонным курдом",
    price: 140,
    tastes: ["лимон"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#fff44f", Bottom: "#fff44f", Center: "#fff9c4" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 5,
    title: "Малиновый макарон",
    description: "Яркий ягодный десерт с малиновым конфитюром",
    price: 155,
    tastes: ["малина"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#e30b5d", Bottom: "#e30b5d", Center: "#f8c8d8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 6,
    title: "Черничный макарон",
    description: "Глубокий ягодный вкус с черничным муссом",
    price: 165,
    tastes: ["черника"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#4a2c5e", Bottom: "#4a2c5e", Center: "#b7a0c9" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 7,
    title: "Ванильный макарон",
    description: "Классический ванильный вкус с кремом из маскарпоне",
    price: 130,
    tastes: ["ваниль"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#f5deb3", Bottom: "#f5deb3", Center: "#fff8ed" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 8,
    title: "Карамельный макарон",
    description: "Солёная карамель с воздушным кремом",
    price: 160,
    tastes: ["карамель"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#c49a2c", Bottom: "#c49a2c", Center: "#fde3a7" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 9,
    title: "Кофейный макарон",
    description: "Эспрессо-макарон с кофейным ганашем",
    price: 175,
    tastes: ["кофе"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#6f4e37", Bottom: "#6f4e37", Center: "#d7b49e" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 10,
    title: "Мятный макарон",
    description: "Освежающий мятный шоколад",
    price: 150,
    tastes: ["мята", "шоколад"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#a8e6cf", Bottom: "#a8e6cf", Center: "#ffffff" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 11,
    title: "Лавандовый макарон",
    description: "Цветочный аромат лаванды с белым шоколадом",
    price: 180,
    tastes: ["лаванда"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#b19cd9", Bottom: "#b19cd9", Center: "#f0e6ff" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 12,
    title: "Апельсиновый макарон",
    description: "Солнечный цитрус с апельсиновым джемом",
    price: 145,
    tastes: ["апельсин"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#ff7f00", Bottom: "#ff7f00", Center: "#ffe0b2" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 13,
    title: "Кокосовый макарон",
    description: "Тропический вкус кокоса и белого шоколада",
    price: 155,
    tastes: ["кокос"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#f5f5dc", Bottom: "#f5f5dc", Center: "#ffffff" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 14,
    title: "Вишневый макарон",
    description: "Кисло-сладкая вишня с шоколадным оттенком",
    price: 160,
    tastes: ["вишня", "шоколад"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#b3002d", Bottom: "#b3002d", Center: "#f4c2c2" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 15,
    title: "Персиковый макарон",
    description: "Сочный персик с нежным сливочным кремом",
    price: 140,
    tastes: ["персик"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#ffcc99", Bottom: "#ffcc99", Center: "#fff2e0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 16,
    title: "Ежевичный макарон",
    description: "Лесная ежевика с темным шоколадом",
    price: 170,
    tastes: ["ежевика", "шоколад"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#3b1f4a", Bottom: "#3b1f4a", Center: "#b280c2" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 17,
    title: "Солёная карамель",
    description: "Интенсивная солёная карамель с хрустящими кристаллами",
    price: 165,
    tastes: ["солёная карамель", "карамель"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#b8860b", Bottom: "#b8860b", Center: "#e6c27a" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 18,
    title: "Розовый лимонад",
    description: "Летнее настроение с нотками малины и лимона",
    price: 145,
    tastes: ["розовый лимонад", "малина", "лимон"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#ff69b4", Bottom: "#ff69b4", Center: "#ffe4e1" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 19,
    title: "Манго-маракуйя",
    description: "Тропический дуэт сладкого манго и кисловатой маракуйи",
    price: 175,
    tastes: ["манго", "маракуйя"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFB347", Bottom: "#FFB347", Center: "#FFF0B3" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 20,
    title: "Голубика",
    description: "Нежная голубика с легким сливочным муссом",
    price: 170,
    tastes: ["голубика"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#3F51B5", Bottom: "#3F51B5", Center: "#C9B1FF" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 21,
    title: "Инжир",
    description: "Спелый инжир с медово-ореховыми нотками",
    price: 185,
    tastes: ["инжир"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#4A0033", Bottom: "#4A0033", Center: "#E6B3CC" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 22,
    title: "Розовый перец",
    description: "Пряный аромат розового перца с белым шоколадом",
    price: 180,
    tastes: ["розовый перец"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#C71585", Bottom: "#C71585", Center: "#FFB6C1" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 23,
    title: "Тирамису",
    description: "Кофейно-сливочный вкус с нотками какао и маскарпоне",
    price: 175,
    tastes: ["тирамису", "кофе"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#5C4033", Bottom: "#5C4033", Center: "#F5DEB3" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 24,
    title: "Пина Колада",
    description: "Кокос и ананас — тропический рай в одном десерте",
    price: 165,
    tastes: ["кокос", "ананас"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFD700", Bottom: "#FFD700", Center: "#FFFFF0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 25,
    title: "Зелёный чай матча",
    description: "Японский чай матча с воздушным сливочным кремом",
    price: 170,
    tastes: ["матча", "зелёный чай"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#5B8C2A", Bottom: "#5B8C2A", Center: "#E0F0D0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 26,
    title: "Личи",
    description: "Экзотический личи с цветочно-медовым ароматом",
    price: 180,
    tastes: ["личи"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#F5A3C7", Bottom: "#F5A3C7", Center: "#FFF0F5" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 27,
    title: "Роза",
    description: "Нежный цветочный вкус розы с малиновым оттенком",
    price: 175,
    tastes: ["роза"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FF66B2", Bottom: "#FF66B2", Center: "#FFE0F0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 28,
    title: "Бергамот",
    description: "Цитрусово-цветочный аромат бергамота с лёгкой горчинкой",
    price: 160,
    tastes: ["бергамот"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#B2C248", Bottom: "#B2C248", Center: "#F5FAD2" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 29,
    title: "Имбирь-лимон",
    description: "Согревающий имбирь и освежающий лимон — яркий контраст",
    price: 155,
    tastes: ["имбирь", "лимон"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#DAA520", Bottom: "#DAA520", Center: "#FFFACD" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 30,
    title: "Банан-шоколад",
    description: "Классическое сочетание банана и молочного шоколада",
    price: 160,
    tastes: ["банан", "шоколад"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFE135", Bottom: "#5C3A21", Center: "#FFF8DC" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 31,
    title: "Киви",
    description: "Сочный киви с лёгкой кислинкой и кремовой текстурой",
    price: 150,
    tastes: ["киви"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#8BC34A", Bottom: "#8BC34A", Center: "#DCEDC8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 32,
    title: "Фисташка-малина",
    description: "Ореховая фисташка и сладкая малина в одном десерте",
    price: 180,
    tastes: ["фисташка", "малина"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#9AC791", Bottom: "#E30B5D", Center: "#F8C8D8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 33,
    title: "Маракуйя",
    description: "Яркая маракуйя с тропическим ганашем",
    price: 170,
    tastes: ["маракуйя"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFB100", Bottom: "#FFB100", Center: "#FFECB3" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 34,
    title: "Чёрная смородина",
    description: "Насыщенный вкус чёрной смородины с белым шоколадом",
    price: 175,
    tastes: ["чёрная смородина"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#2E0854", Bottom: "#2E0854", Center: "#D8BFD8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 35,
    title: "Клюква",
    description: "Клюква с воздушным сливочным кремом и кислинкой",
    price: 165,
    tastes: ["клюква"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#9B111E", Bottom: "#9B111E", Center: "#FFB6C1" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 36,
    title: "Кленовый сироп",
    description: "Сладкий кленовый сироп с ореховым акцентом",
    price: 160,
    tastes: ["кленовый сироп"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#C49A2C", Bottom: "#C49A2C", Center: "#FFE4B5" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 37,
    title: "Тыква-специи",
    description: "Осенний тыквенный латте с пряностями",
    price: 170,
    tastes: ["тыква", "специи"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FF7518", Bottom: "#FF7518", Center: "#FFDAB9" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 38,
    title: "Красный апельсин",
    description: "Сладкий красный апельсин с тонкой горчинкой",
    price: 165,
    tastes: ["апельсин", "красный апельсин"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FF4500", Bottom: "#FF4500", Center: "#FFDAB9" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 39,
    title: "Грейпфрут",
    description: "Розовый грейпфрут с освежающей кислинкой",
    price: 155,
    tastes: ["грейпфрут"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FF6B6B", Bottom: "#FF6B6B", Center: "#FFE0E0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 40,
    title: "Шоколад-чили",
    description: "Тёмный шоколад с острым перцем чили",
    price: 180,
    tastes: ["шоколад", "чили"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#4A1F1F", Bottom: "#4A1F1F", Center: "#FFB6C1" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 41,
    title: "Кокос-лайм",
    description: "Кокосовый крем с цедрой лайма",
    price: 165,
    tastes: ["кокос", "лайм"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#F5F5DC", Bottom: "#32CD32", Center: "#FFFFFF" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 42,
    title: "Абрикос",
    description: "Сочный абрикос с ванильным кремом",
    price: 145,
    tastes: ["абрикос"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFB347", Bottom: "#FFB347", Center: "#FFE5B4" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 43,
    title: "Арбуз",
    description: "Освежающий арбуз с лёгкой мятной ноткой",
    price: 140,
    tastes: ["арбуз"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FF3B3B", Bottom: "#2E8B57", Center: "#FFFFFF" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 44,
    title: "Крем-брюле",
    description: "Карамелизированный сахар и нежный заварной крем",
    price: 175,
    tastes: ["крем-брюле", "карамель"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#DAA520", Bottom: "#DAA520", Center: "#FFFACD" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 45,
    title: "Ром-изюм",
    description: "Выдержанный ром с сочным изюмом",
    price: 190,
    tastes: ["ром", "изюм"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#3E2723", Bottom: "#3E2723", Center: "#D7CCC8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 46,
    title: "Марципан",
    description: "Сладкий миндальный марципан с розовой водой",
    price: 185,
    tastes: ["марципан", "миндаль"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFE4B5", Bottom: "#FFE4B5", Center: "#FFF8DC" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 47,
    title: "Солёный попкорн",
    description: "Карамелизированный попкорн с морской солью",
    price: 150,
    tastes: ["попкорн", "карамель"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFFACD", Bottom: "#FFFACD", Center: "#FFFFF0" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 48,
    title: "Чай Эрл Грей",
    description: "Чёрный чай с бергамотом и молочной пенкой",
    price: 170,
    tastes: ["чай", "бергамот"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#4A3B32", Bottom: "#4A3B32", Center: "#E6D3C8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 49,
    title: "Мёд-лаванда",
    description: "Цветочный мёд с лавандой — успокаивающее сочетание",
    price: 180,
    tastes: ["мёд", "лаванда"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFD700", Bottom: "#B19CD9", Center: "#F0E6FF" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
  {
    id: 50,
    title: "Белый шоколад-малина",
    description: "Белый шоколад с малиновым конфитюром внутри",
    price: 175,
    tastes: ["белый шоколад", "малина"],
    macaronConfig: {
      camera: { position: [0, 0, 5] as [number, number, number] },
      environment: { map: null, intensity: 20 },
      light: { position: [0, 3, 3] as [number, number, number], intensity: 8 },
      macaronConfig: {
        colors: { Top: "#FFFFFF", Bottom: "#E30B5D", Center: "#F8C8D8" },
        position: [0, 0, 0] as [number, number, number],
        speed: 0.8,
      },
    },
  },
];